# PR 자동 라벨링 설정

# 소스 코드 영역별
'area: threading':
  - src/**/Threading/**/*
  - tests/**/Threading/**/*

'area: linq':
  - src/**/Linq/**/*
  - tests/**/Linq/**/*

'area: collections':
  - src/**/Collections/**/*
  - tests/**/Collections/**/*

'area: async':
  - src/**/Async*.cs
  - src/**/Task*.cs
  - src/**/CompilerServices/**/*
  - tests/**/Async*.cs
  - tests/**/Task*.cs

'area: delegates':
  - src/**/Action.cs
  - src/**/Func.cs
  - src/**/Predicate.cs

'area: tuples':
  - src/**/Tuple*.cs
  - src/**/ValueTuple*.cs
  - tests/**/Tuple*.cs

'area: memory':
  - src/**/Span*.cs
  - src/**/Memory*.cs
  - src/**/Buffers/**/*
  - tests/**/Span*.cs
  - tests/**/Memory*.cs

'area: compiler':
  - src/**/CompilerServices/**/*
  - src/**/Attributes/**/*

# 변경 타입
'type: feature':
  - any: ['src/**/*.cs']
    all: ['!tests/**/*.cs']

'type: tests':
  - tests/**/*

'type: docs':
  - '**/*.md'
  - docs/**/*

'type: ci':
  - .github/workflows/**/*
  - .github/**/*.yml

'type: build':
  - '**/*.csproj'
  - '**/*.props'
  - '**/*.targets'
  - Directory.Build.*

# 프레임워크 타겟
'framework: net35':
  - any: ['**/*']
    all:
      - '**/#if NET35'
      - '**/#elif NET35'

'framework: net40':
  - any: ['**/*']
    all:
      - '**/#if NET40'
      - '**/#elif NET40'

'framework: netstandard':
  - any: ['**/*']
    all:
      - '**/#if NETSTANDARD'
